id: A6F8868F2
title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
  for Mind Training'
type: translation
pechas:
- I9DD4804B
- IB4918B3C
- IA88E2891
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:35:24.033280
  last_modified_at: 2023-01-04 11:35:24.033295
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I9DD4804B/B2F7: '2496'
  IB4918B3C/FA24: '2496'
  IA88E2891/6A8B: '2496'
